### ISSUE TITLE
Structure learning algorithms have very unstable performance

### ISSUE THREAD

**Issue by itschenxi** [erdogant/bnlearn#92]
Hi,

I am testing bnlearn and found that the structure learning algorithms are very unstable, sometimes they generate very accurate results, sometimes very inaccurate results. I am testing the asia example and the searching algorithms include hc and cs, scoretype="bic". Could anybody explain why? Is it because of random? Thank you very much indeed.

```
model_true=bn.import_DAG('asia')
df=bn.sampling(model_true, n=10000)
model_learned=bn.structure_learning.fit(df)
bn.compare_networks(model_true, model_learned)

```

**Comment by erdogant** [comment]
This can happen due to the stochastic component thats in the algorithms. The starting position of the search space is (usually) random which means that it can become stuck in a local optimum. In addition, if you would use different algorithms, they would likely also return (slightly) different results. One way to be more confident about the results it is by running it a few times and (testing) whether a structure is more often returned. The best way to validate the results is using an external source. For example when using genes, you would like to perform a real lab experiment.

**Comment by erdogant** [comment]
If there is anything else, let me know.
